#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['click']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

extras_require = \
{":platform_system == 'Windows'": ['colorama'],
 ":python_version < '3.8'": ['importlib-metadata']}

setup(name='click',
      version='8.1.8',
      description='Composable command line interface toolkit',
      author=None,
      author_email=None,
      url=None,
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      extras_require=extras_require,
      python_requires='>=3.7',
     )
