#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['click']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

setup(name='click',
      version='8.5.0',
      description='Composable command line interface toolkit',
      author=None,
      author_email=None,
      url=None,
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      python_requires='>=3.10',
     )
